/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "EMGSig_aliases.h"
#include "EMGSig.h"
#include "UART_1.h"
#include "ADC_SAR_1.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "PWM_2.h"
#include "Index_Finger_aliases.h"
#include "Index_Finger.h"
#include "PWM_3.h"
#include "Middle_Finger_aliases.h"
#include "Middle_Finger.h"
#include "PWM_4.h"
#include "Ring_Finger_aliases.h"
#include "Ring_Finger.h"
#include "Pinky_Finger_aliases.h"
#include "Pinky_Finger.h"
#include "PWM_5.h"
#include "Thumb_Finger_aliases.h"
#include "Thumb_Finger.h"
#include "Timer_1.h"
#include "ISR_VERIFY.h"
#include "Timer_2.h"
#include "ISR_SAMPLE.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

